CREATE TABLE IF NOT EXISTS roles (id BIGSERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL);
INSERT INTO roles (name) VALUES ('ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
